### PR TITLE
fix voc name in combined tfidf

### LINKED ISSUE #5: Combined features file does not have associated vocabulary
`data-neuroquery_version-1_vocab-neuroquery7547_source-combined_type-tfidf_features.npz` and `data-neuroquery_version-1_vocab-neuroquery7547_vocabulary.txt` don't match up because the combined features file has 6308 features. I know that that file uses a vocabulary that combines synonyms in 7547, but I don't know where that vocabulary is.

Could we (1) rename the combined features to have `vocab-neuroquery6308` and (2) add a new `data-neuroquery_version-1_vocab-neuroquery6308_vocabulary.txt` file?

### PR DESCRIPTION
**Pull request by jeromedockes**
closes #5

### CODE REVIEW

**Comment by jeromedockes** [comment]
@tsalo if you have time please have a look, otherwise I will merge it

**Comment by tsalo** [comment]
Thanks! I'll test out the conversion now.

**Comment by tsalo** [comment]
The conversion to a NiMARE Dataset ran without issue, so I think this is good to merge.

**Comment by jeromedockes** [comment]
thank you! I'll merge it then

**Pull request merged**
